import type { Role } from "@/lib/types";

import type { TourStep } from "./types";

// Role sets mirror NAV in lib/nav.ts, so nobody is walked to a page they cannot open.
const REVIEW: Role[] = ["analyst", "supervisor"];
const AUDIT: Role[] = ["supervisor", "admin"];

export const TOUR_STEPS: TourStep[] = [
  // Welcome
  {
    id: "welcome",
    chapter: "Welcome",
    title: "Welcome to FraudLens",
    body: "Every upay payment is scored in real time: allowed, warned, held or blocked. This tour shows where those decisions land and how your team acts on them.",
  },

  // Navigation
  {
    id: "brand",
    chapter: "Navigation",
    target: "brand",
    mobileTarget: "bottom-nav",
    placement: "right",
    title: "Your console",
    body: "The sidebar is grouped by job: business impact, investigation, the mule network, model governance and the customer view.",
  },
  {
    id: "nav-investigate",
    chapter: "Navigation",
    target: "nav-group-investigate",
    mobileTarget: "tab-alerts",
    placement: "right",
    action: "hover",
    roles: REVIEW,
    title: "Day-to-day work",
    body: "Alerts, cases, freezes, appeals and refunds: the queues an analyst clears every shift.",
  },
  {
    id: "nav-governance",
    chapter: "Navigation",
    target: "nav-group-model-and-policy",
    mobileTarget: "tab-model",
    placement: "right",
    action: "hover",
    roles: ["admin"],
    title: "Governance first",
    body: "As an admin you own the model, the policy and the audit trail. Investigation queues stay with analysts and supervisors.",
  },
  {
    id: "serving",
    chapter: "Navigation",
    target: "serving",
    mobileTarget: "bottom-nav",
    placement: "right",
    title: "What is deciding right now",
    body: "The live model and policy versions. If the model goes down this turns amber and decisions fall back to rules alone.",
  },

  // Overview
  {
    id: "home-kpis",
    chapter: "Overview",
    route: "/",
    target: "home-kpis",
    placement: "bottom",
    action: "hover",
    title: "Executive summary",
    body: "Live decisions, interrupted payments and taka stopped, refreshed as traffic arrives.",
  },
  {
    id: "impact",
    chapter: "Overview",
    route: "/impact",
    target: "impact-simulator",
    placement: "bottom",
    action: "hover",
    title: "Impact simulator",
    body: "Drag the alert threshold to see the trade-off: victims' money saved against honest customers interrupted and reviewer load.",
  },

  // Operations
  {
    id: "alerts",
    chapter: "Operations",
    route: "/alerts",
    target: "alerts-queue",
    placement: "top",
    action: "hover",
    roles: REVIEW,
    title: "Alert queue",
    body: "Held and blocked payments stream in live, highest risk first. Filter by tier or status and open one to see why it fired.",
  },
  {
    id: "cases",
    chapter: "Operations",
    route: "/cases",
    target: "cases-list",
    placement: "top",
    action: "hover",
    roles: REVIEW,
    title: "Cases",
    body: "Alerts on the same wallet roll up into one case with a review deadline. A person records every verdict; those verdicts retrain the model.",
  },
  {
    id: "approvals",
    chapter: "Operations",
    route: "/approvals",
    target: "approvals-queue",
    placement: "top",
    action: "hover",
    roles: REVIEW,
    title: "Freeze approvals",
    body: "Freezing a wallet takes two people: an analyst asks, a supervisor approves. Ring proposals arrive together but are decided wallet by wallet.",
  },
  {
    id: "appeals",
    chapter: "Operations",
    route: "/appeals",
    target: "appeals-queue",
    placement: "top",
    action: "hover",
    roles: REVIEW,
    title: "Customer appeals",
    body: "Customers who think a hold was wrong appeal from the app. Each has a deadline, and late ones are flagged.",
  },
  {
    id: "refunds",
    chapter: "Operations",
    route: "/refunds",
    target: "refunds-queue",
    placement: "top",
    action: "hover",
    roles: REVIEW,
    title: "Victim refunds",
    body: "Once fraud is confirmed and the mule wallet frozen, victims are repaid from what is left in it, tracked to a promised date.",
  },

  // Investigation
  {
    id: "network",
    chapter: "Investigation",
    route: "/network",
    target: "network-search",
    placement: "bottom",
    action: "hover",
    roles: REVIEW,
    title: "Network explorer",
    body: "Look up any wallet to see who it pays, who pays it and which handsets it shares.",
  },
  {
    id: "rings",
    chapter: "Investigation",
    route: "/rings",
    target: "rings-table",
    placement: "top",
    action: "hover",
    roles: REVIEW,
    title: "Mule rings",
    body: "Wallets tied by shared handsets and internal transfers, ranked by money received. Freeze a whole ring in one proposal.",
  },
  {
    id: "consortium",
    chapter: "Investigation",
    route: "/consortium",
    target: "consortium-kpis",
    placement: "bottom",
    action: "hover",
    roles: REVIEW,
    title: "Mule consortium",
    body: "Providers share signed, tokenised mule listings, so a mule flagged by another provider is known here before it receives a victim's money.",
  },
  {
    id: "agents",
    chapter: "Investigation",
    route: "/agents",
    target: "agents-table",
    placement: "top",
    action: "hover",
    roles: REVIEW,
    title: "Agent risk",
    body: "Cash-out agents ranked by risk, with what stands out about each. This is where stolen money usually leaves the system.",
  },

  // Governance
  {
    id: "model",
    chapter: "Governance",
    route: "/model",
    target: "model-kpis",
    placement: "bottom",
    action: "hover",
    title: "Model monitoring",
    body: "Precision, recall and money stopped on held-out weeks, plus drift and the shadow model waiting to replace it.",
  },
  {
    id: "fairness",
    chapter: "Governance",
    route: "/fairness",
    target: "fairness-kpis",
    placement: "bottom",
    action: "hover",
    title: "Fairness report",
    body: "How often honest customers are interrupted, broken down by sender and receiver group, so no group carries more friction than another.",
  },
  {
    id: "policy",
    chapter: "Governance",
    route: "/policy",
    target: "policy-tiers",
    placement: "bottom",
    action: "hover",
    title: "Decision policy",
    body: "Score thresholds per tier, what the customer sees, and the rules that can only raise a tier, never lower it.",
  },
  {
    id: "fraud-types",
    chapter: "Governance",
    route: "/fraud-types",
    target: "fraud-types-header",
    placement: "bottom",
    title: "Fraud types",
    body: "Coverage by scam type, and a live checker for Bangla, Banglish and English scam messages.",
  },
  {
    id: "audit",
    chapter: "Governance",
    route: "/audit",
    target: "audit-log",
    placement: "top",
    action: "hover",
    roles: AUDIT,
    title: "Audit log",
    body: "Every verdict, freeze, refund and identity reveal, with who did it and from where. Nothing in the console is unrecorded.",
  },

  // Customer demo
  {
    id: "nav-phone",
    chapter: "Customer demo",
    target: "nav-phone",
    mobileTarget: "tab-more",
    placement: "right",
    action: "click",
    title: "See the customer side",
    body: "Open the phone demo to watch a payment from the sender's point of view.",
  },
  {
    id: "phone",
    chapter: "Customer demo",
    route: "/phone",
    target: "phone-device",
    placement: "left",
    action: "hover",
    title: "What the customer sees",
    body: "Pick a payment and send it: the upay app shows the warning, hold or block in Bangla or English, with a one-tap scam report.",
  },

  // Finish
  {
    id: "tour-button",
    chapter: "Finish",
    target: "tour-button",
    placement: "right",
    action: "hover",
    title: "Re-run anytime",
    body: "Start this tour again from here whenever you need a refresher.",
  },
  {
    id: "done",
    chapter: "Finish",
    title: "Where to start",
    body: "Start with the highest-risk item in your queue. Every action you take is audited and feeds the next model.",
  },
];
