import type { Role } from "@/lib/types";

import type { TourStep } from "./types";

// Role sets mirror NAV in lib/nav.ts, so nobody is walked to a page they cannot open.
const REVIEW: Role[] = ["analyst", "supervisor"];
const AUDIT: Role[] = ["supervisor", "admin"];

export const TOUR_STEPS: TourStep[] = [
  // Welcome
  {
    id: "welcome",
    chapter: "Welcome",
    title: "Welcome to FraudLens",
    body: "We check every upay payment for fraud as it happens. This tour can play by itself, and you can switch language anytime with the EN / বাংলা button.",
    titleBn: "FraudLens-এ স্বাগতম",
    bodyBn: "প্রতিটা upay পেমেন্ট আমরা সাথে সাথে প্রতারণার জন্য চেক করি। ট্যুরটা নিজে নিজেই চলতে পারে, আর EN / বাংলা বাটনে চাপ দিয়ে যেকোনো সময় ভাষা বদলাতে পারবেন।",
  },

  // Navigation
  {
    id: "brand",
    chapter: "Navigation",
    target: "brand",
    mobileTarget: "bottom-nav",
    placement: "right",
    title: "Your main menu",
    body: "This menu takes you everywhere. Pages are grouped by job: results, investigation, criminal networks, AI settings and the customer view.",
    titleBn: "আপনার মূল মেনু",
    bodyBn: "এই মেনু দিয়ে সব জায়গায় যাওয়া যায়। পেজগুলো কাজ অনুযায়ী সাজানো: ফলাফল, তদন্ত, প্রতারক চক্র, AI সেটিংস আর গ্রাহকের দিক।",
  },
  {
    id: "nav-investigate",
    chapter: "Navigation",
    target: "nav-group-investigate",
    mobileTarget: "tab-alerts",
    placement: "right",
    action: "hover",
    roles: REVIEW,
    title: "Your daily work",
    body: "Here are the lists your team works through every day: suspicious payments, cases, account freezes, customer complaints and refunds.",
    titleBn: "প্রতিদিনের কাজ",
    bodyBn: "আপনার টিম প্রতিদিন যে কাজগুলো করে সেগুলো এখানে: সন্দেহজনক পেমেন্ট, কেস, অ্যাকাউন্ট ফ্রিজ, গ্রাহকের অভিযোগ আর রিফান্ড।",
  },
  {
    id: "nav-governance",
    chapter: "Navigation",
    target: "nav-group-model-and-policy",
    mobileTarget: "tab-model",
    placement: "right",
    action: "hover",
    roles: ["admin"],
    title: "Your admin area",
    body: "As an admin, you look after the AI that scores payments, the rules it follows and the record of who did what.",
    titleBn: "অ্যাডমিন অংশ",
    bodyBn: "অ্যাডমিন হিসেবে আপনি দেখবেন পেমেন্ট যাচাই করা AI, সেটা কোন নিয়মে চলে, আর কে কী করেছে তার রেকর্ড।",
  },
  {
    id: "serving",
    chapter: "Navigation",
    target: "serving",
    mobileTarget: "bottom-nav",
    placement: "right",
    title: "Is the AI working?",
    body: "This shows which AI version is checking payments now. If it turns amber, the AI is down and simple backup rules take over.",
    titleBn: "AI কি চালু আছে?",
    bodyBn: "এখন কোন AI ভার্সন পেমেন্ট চেক করছে তা এখানে দেখা যায়। হলুদ হয়ে গেলে বুঝবেন AI বন্ধ, তখন সাধারণ ব্যাকআপ নিয়মে কাজ চলে।",
  },

  // Overview
  {
    id: "home-kpis",
    chapter: "Overview",
    route: "/",
    target: "home-kpis",
    placement: "bottom",
    action: "hover",
    title: "Today at a glance",
    body: "This shows how many payments were checked, how many were stopped and how much money (in taka) was saved. It updates live.",
    titleBn: "এক নজরে আজকের অবস্থা",
    bodyBn: "কতগুলো পেমেন্ট চেক হলো, কতগুলো আটকানো হলো আর কত টাকা বাঁচানো গেল, সব এখানে। সংখ্যাগুলো লাইভ আপডেট হয়।",
  },
  {
    id: "impact",
    chapter: "Overview",
    route: "/impact",
    target: "impact-simulator",
    placement: "bottom",
    action: "hover",
    title: "Try \"what if\"",
    body: "Move the slider to be stricter or softer. You see how much money is saved versus how many honest customers get stopped.",
    titleBn: "\"যদি এমন হয়\" দেখে নিন",
    bodyBn: "স্লাইডারটা সরিয়ে কড়া বা নরম করে দেখুন। কত টাকা বাঁচে আর কতজন সৎ গ্রাহক অকারণে আটকে যায়, তা সাথে সাথে দেখা যাবে।",
  },

  // Operations
  {
    id: "alerts",
    chapter: "Operations",
    route: "/alerts",
    target: "alerts-queue",
    placement: "top",
    action: "hover",
    roles: REVIEW,
    title: "Suspicious payments",
    body: "Payments we held or blocked appear here live, riskiest first. Click one to see why it looked suspicious.",
    titleBn: "সন্দেহজনক পেমেন্ট",
    bodyBn: "যেসব পেমেন্ট আটকানো হয়েছে সেগুলো এখানে লাইভ আসে, সবচেয়ে ঝুঁকিপূর্ণগুলো আগে। কেন সন্দেহ হলো দেখতে যেকোনো একটায় ক্লিক করুন।",
  },
  {
    id: "cases",
    chapter: "Operations",
    route: "/cases",
    target: "cases-list",
    placement: "top",
    action: "hover",
    roles: REVIEW,
    title: "Cases",
    body: "Alerts about the same account are grouped into one case. A person decides each one, and those decisions help the AI learn.",
    titleBn: "কেস",
    bodyBn: "একই অ্যাকাউন্টের সব অ্যালার্ট মিলে একটা কেস হয়। প্রতিটা কেসে সিদ্ধান্ত নেন একজন মানুষ, আর সেই সিদ্ধান্ত থেকে AI শেখে।",
  },
  {
    id: "approvals",
    chapter: "Operations",
    route: "/approvals",
    target: "approvals-queue",
    placement: "top",
    action: "hover",
    roles: REVIEW,
    title: "Freezing an account",
    body: "Freezing an account needs two people: one asks, a senior approves. Even for a whole gang, each account is checked one by one.",
    titleBn: "অ্যাকাউন্ট ফ্রিজ করা",
    bodyBn: "অ্যাকাউন্ট ফ্রিজ করতে দুজন লাগে: একজন অনুরোধ করেন, একজন সিনিয়র অনুমোদন দেন। পুরো চক্র হলেও প্রতিটা অ্যাকাউন্ট আলাদা করে দেখা হয়।",
  },
  {
    id: "appeals",
    chapter: "Operations",
    route: "/appeals",
    target: "appeals-queue",
    placement: "top",
    action: "hover",
    roles: REVIEW,
    title: "Customer complaints",
    body: "If a customer thinks we stopped their payment by mistake, they can complain from the app. Each one has a deadline; late ones are marked.",
    titleBn: "গ্রাহকের অভিযোগ",
    bodyBn: "গ্রাহকের মনে হলে যে ভুল করে পেমেন্ট আটকানো হয়েছে, অ্যাপ থেকেই অভিযোগ করতে পারেন। প্রতিটার সময়সীমা আছে, দেরি হলে চিহ্ন পড়ে যায়।",
  },
  {
    id: "refunds",
    chapter: "Operations",
    route: "/refunds",
    target: "refunds-queue",
    placement: "top",
    action: "hover",
    roles: REVIEW,
    title: "Paying victims back",
    body: "Once fraud is confirmed, we freeze the criminal's account and return what's left to victims. You can track each refund until it's paid.",
    titleBn: "ক্ষতিগ্রস্তদের টাকা ফেরত",
    bodyBn: "প্রতারণা নিশ্চিত হলে প্রতারকের অ্যাকাউন্ট ফ্রিজ করে বাকি টাকা ক্ষতিগ্রস্তদের ফেরত দেওয়া হয়। টাকা পৌঁছানো পর্যন্ত প্রতিটা রিফান্ড ট্র্যাক করা যায়।",
  },

  // Investigation
  {
    id: "network",
    chapter: "Investigation",
    route: "/network",
    target: "network-search",
    placement: "bottom",
    action: "hover",
    roles: REVIEW,
    title: "Who's connected?",
    body: "Search any account to see who it sends money to, who sends to it, and which phones it shares with others.",
    titleBn: "কার সাথে কার যোগাযোগ?",
    bodyBn: "যেকোনো অ্যাকাউন্ট সার্চ করে দেখুন সে কাকে টাকা পাঠায়, কে তাকে পাঠায়, আর অন্য কার সাথে একই ফোন ব্যবহার করে।",
  },
  {
    id: "rings",
    chapter: "Investigation",
    route: "/rings",
    target: "rings-table",
    placement: "top",
    action: "hover",
    roles: REVIEW,
    title: "Criminal gangs",
    body: "Groups of accounts criminals use to move stolen money, linked by shared phones. You can ask to freeze a whole gang at once.",
    titleBn: "প্রতারক চক্র",
    bodyBn: "চুরির টাকা সরাতে প্রতারকরা যে অ্যাকাউন্টগুলো ব্যবহার করে, একই ফোনের সূত্রে সেগুলোকে এক দলে দেখানো হয়। পুরো চক্র একবারে ফ্রিজের অনুরোধ করা যায়।",
  },
  {
    id: "consortium",
    chapter: "Investigation",
    route: "/consortium",
    target: "consortium-kpis",
    placement: "bottom",
    action: "hover",
    roles: REVIEW,
    title: "Shared blacklist",
    body: "Payment companies safely share lists of criminal accounts. So if another company catches one, we know before it gets a victim's money.",
    titleBn: "সবার শেয়ার করা কালো তালিকা",
    bodyBn: "পেমেন্ট কোম্পানিগুলো নিরাপদে প্রতারকদের অ্যাকাউন্টের তালিকা শেয়ার করে। অন্য কেউ ধরলে, টাকা যাওয়ার আগেই আমরা জেনে যাই।",
  },
  {
    id: "agents",
    chapter: "Investigation",
    route: "/agents",
    target: "agents-table",
    placement: "top",
    action: "hover",
    roles: REVIEW,
    title: "Risky cash-out agents",
    body: "Shops where people turn wallet money into cash, riskiest first. This is usually where stolen money leaves the system.",
    titleBn: "ঝুঁকিপূর্ণ ক্যাশ-আউট এজেন্ট",
    bodyBn: "যেসব দোকানে ওয়ালেটের টাকা ক্যাশ করা হয়, ঝুঁকি অনুযায়ী সাজানো। চুরির টাকা সাধারণত এখান দিয়েই বেরিয়ে যায়।",
  },

  // Governance
  {
    id: "model",
    chapter: "Governance",
    route: "/model",
    target: "model-kpis",
    placement: "bottom",
    action: "hover",
    title: "How well is the AI doing?",
    body: "This shows how often the AI catches real fraud, how often it's wrong, and whether it's getting worse. A newer AI is tested here too.",
    titleBn: "AI কেমন কাজ করছে?",
    bodyBn: "AI কতবার আসল প্রতারণা ধরছে, কতবার ভুল করছে, আর দিন দিন খারাপ হচ্ছে কিনা, তা এখানে দেখা যায়। নতুন AI-ও এখানে পরীক্ষা হয়।",
  },
  {
    id: "fairness",
    chapter: "Governance",
    route: "/fairness",
    target: "fairness-kpis",
    placement: "bottom",
    action: "hover",
    title: "Is it fair to everyone?",
    body: "This checks that no group of customers gets stopped by mistake more often than others.",
    titleBn: "সবার প্রতি কি সমান আচরণ?",
    bodyBn: "কোনো এক ধরনের গ্রাহক যেন অন্যদের চেয়ে বেশি অকারণে আটকে না যায়, সেটা এখানে যাচাই করা হয়।",
  },
  {
    id: "policy",
    chapter: "Governance",
    route: "/policy",
    target: "policy-tiers",
    placement: "bottom",
    action: "hover",
    title: "The rules",
    body: "Here you set when a payment is warned, held or blocked, and what the customer sees. Extra rules can only make it stricter.",
    titleBn: "নিয়মকানুন",
    bodyBn: "কখন পেমেন্টে সতর্কতা দেবে, আটকাবে বা ব্লক করবে, আর গ্রাহক কী দেখবেন, এখানে ঠিক হয়। বাড়তি নিয়ম শুধু কড়াই করতে পারে।",
  },
  {
    id: "fraud-types",
    chapter: "Governance",
    route: "/fraud-types",
    target: "fraud-types-header",
    placement: "bottom",
    title: "Types of scams",
    body: "See which kinds of scams we catch. You can also paste a message in Bangla, Banglish or English to check if it's a scam.",
    titleBn: "প্রতারণার ধরন",
    bodyBn: "কোন কোন ধরনের প্রতারণা আমরা ধরি, দেখে নিন। বাংলা, বাংলিশ বা ইংরেজিতে কোনো মেসেজ পেস্ট করে চেক করতে পারবেন সেটা প্রতারণা কিনা।",
  },
  {
    id: "audit",
    chapter: "Governance",
    route: "/audit",
    target: "audit-log",
    placement: "top",
    action: "hover",
    roles: AUDIT,
    title: "Who did what",
    body: "Every decision, freeze and refund is recorded here, with who did it and from where. Nothing happens without a record.",
    titleBn: "কে কী করেছে",
    bodyBn: "প্রতিটা সিদ্ধান্ত, ফ্রিজ আর রিফান্ড এখানে লেখা থাকে, কে করেছে আর কোথা থেকে করেছে সহ। রেকর্ড ছাড়া কিছুই হয় না।",
  },

  // Customer demo
  {
    id: "nav-phone",
    chapter: "Customer demo",
    target: "nav-phone",
    mobileTarget: "tab-more",
    placement: "right",
    action: "click",
    title: "See the customer side",
    body: "Open the phone demo to see a payment the way a customer sees it.",
    titleBn: "গ্রাহকের দিকটা দেখুন",
    bodyBn: "ফোন ডেমো খুলে দেখুন, একজন গ্রাহক তার ফোনে পেমেন্টটা কেমন দেখেন।",
  },
  {
    id: "phone",
    chapter: "Customer demo",
    route: "/phone",
    target: "phone-device",
    placement: "left",
    action: "hover",
    title: "What the customer sees",
    body: "Pick a payment and send it. The upay app shows a warning or stops it, in Bangla or English, with a one-tap button to report a scam.",
    titleBn: "গ্রাহক যা দেখেন",
    bodyBn: "একটা পেমেন্ট বেছে পাঠিয়ে দেখুন। upay অ্যাপ বাংলা বা ইংরেজিতে সতর্ক করে বা আটকে দেয়, আর এক ট্যাপেই প্রতারণা রিপোর্ট করা যায়।",
  },

  // Finish
  {
    id: "tour-button",
    chapter: "Finish",
    target: "tour-button",
    placement: "right",
    action: "hover",
    title: "Watch again anytime",
    body: "Click here whenever you want to take this tour again.",
    titleBn: "আবার দেখতে চাইলে",
    bodyBn: "যখনই আবার ট্যুরটা দেখতে চান, এখানে ক্লিক করুন।",
  },
  {
    id: "done",
    chapter: "Finish",
    title: "Where to begin",
    body: "Start with the riskiest item at the top of your list. Everything you do is recorded and helps the AI get smarter.",
    titleBn: "কোথা থেকে শুরু করবেন",
    bodyBn: "আপনার তালিকার একদম ওপরের, সবচেয়ে ঝুঁকিপূর্ণ কাজটা দিয়ে শুরু করুন। আপনার প্রতিটা কাজ রেকর্ড হয় আর AI-কে আরও স্মার্ট করে।",
  },
];
