"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-01 16:17:55.032199

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("agent_id", sa.String(length=32), nullable=False),
        sa.Column("district", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("agent_id", name=op.f("pk_agents")),
    )
    op.create_table(
        "past_cases",
        sa.Column("case_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("typology", sa.String(length=32), nullable=False),
        sa.Column("victim_id", sa.String(length=32), nullable=False),
        sa.Column("mule_id", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("loss", sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=False),
        sa.Column("n_txn", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("case_id", name=op.f("pk_past_cases")),
    )
    op.create_index(op.f("ix_past_cases_mule_id"), "past_cases", ["mule_id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("txn_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("sender_id", sa.String(length=32), nullable=False),
        sa.Column("sender_type", sa.String(length=16), nullable=False),
        sa.Column("receiver_id", sa.String(length=32), nullable=False),
        sa.Column("receiver_type", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=False),
        sa.Column(
            "sender_balance_before",
            sa.Numeric(precision=14, scale=2, asdecimal=False),
            nullable=True,
        ),
        sa.Column("device_id", sa.String(length=64), server_default="", nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("district", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("status_reason", sa.String(length=40), nullable=True),
        sa.Column("source", sa.String(length=8), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("applied_seq", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('history', 'replay', 'live')", name=op.f("ck_transactions_source")
        ),
        sa.CheckConstraint(
            "status IN "
            "('completed', 'pending_customer', 'held', 'cancelled', 'blocked', 'rejected')",
            name=op.f("ck_transactions_status"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_transactions_amount_positive")),
        sa.PrimaryKeyConstraint("txn_id", name=op.f("pk_transactions")),
    )
    op.create_index(
        "ix_transactions_applied",
        "transactions",
        ["applied_seq"],
        unique=False,
        postgresql_where=sa.text("applied_seq IS NOT NULL"),
    )
    op.create_index(
        "ix_transactions_receiver_ts", "transactions", ["receiver_id", "ts"], unique=False
    )
    op.create_index("ix_transactions_sender_ts", "transactions", ["sender_id", "ts"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('analyst', 'supervisor', 'admin', 'service')", name=op.f("ck_users_role")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "wallets",
        sa.Column("wallet_id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("district", sa.String(length=40), nullable=False),
        sa.Column("area_type", sa.String(length=16), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("segment", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('active', 'frozen')", name=op.f("ck_wallets_status")),
        sa.PrimaryKeyConstraint("wallet_id", name=op.f("pk_wallets")),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=True),
        sa.Column("action", sa.String(length=48), nullable=False),
        sa.Column("object_type", sa.String(length=24), nullable=True),
        sa.Column("object_id", sa.String(length=64), nullable=True),
        sa.Column(
            "detail",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_audit_log_actor_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(op.f("ix_audit_log_at"), "audit_log", ["at"], unique=False)
    op.create_index("ix_audit_log_object", "audit_log", ["object_type", "object_id"], unique=False)
    op.create_table(
        "cases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject_id", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="open", nullable=False),
        sa.Column("priority", sa.String(length=8), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("assigned_to", sa.Integer(), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sla_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verdict", sa.String(length=20), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'closed') = (verdict IS NOT NULL)", name=op.f("ck_cases_closed_has_verdict")
        ),
        sa.CheckConstraint(
            "source IN ('alert', 'customer_report', 'manual')", name=op.f("ck_cases_source")
        ),
        sa.CheckConstraint(
            "status IN ('open', 'in_review', 'escalated', 'closed')", name=op.f("ck_cases_status")
        ),
        sa.CheckConstraint(
            "verdict IS NULL OR verdict IN ('confirmed_fraud', 'legitimate', 'inconclusive')",
            name=op.f("ck_cases_verdict"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"], ["users.id"], name=op.f("fk_cases_assigned_to_users")
        ),
        sa.ForeignKeyConstraint(["closed_by"], ["users.id"], name=op.f("fk_cases_closed_by_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cases")),
    )
    op.create_index("ix_cases_status_sla", "cases", ["status", "sla_due_at"], unique=False)
    op.create_index(
        "uq_cases_open_subject",
        "cases",
        ["subject_id"],
        unique=True,
        postgresql_where=sa.text("status <> 'closed'"),
    )
    op.create_table(
        "case_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_case_events_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_case_events_case_id_cases"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_events")),
    )
    op.create_index(op.f("ix_case_events_case_id"), "case_events", ["case_id"], unique=False)
    op.create_table(
        "customer_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reporter_id", sa.String(length=32), nullable=False),
        sa.Column("reported_wallet_id", sa.String(length=32), nullable=False),
        sa.Column("txn_id", sa.BigInteger(), nullable=True),
        sa.Column("category", sa.String(length=24), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=True),
        sa.Column("reported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_customer_reports_case_id_cases")
        ),
        sa.ForeignKeyConstraint(
            ["txn_id"],
            ["transactions.txn_id"],
            name=op.f("fk_customer_reports_txn_id_transactions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_reports")),
    )
    op.create_index(
        op.f("ix_customer_reports_reported_wallet_id"),
        "customer_reports",
        ["reported_wallet_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_reports_reporter_id"), "customer_reports", ["reporter_id"], unique=False
    )
    op.create_table(
        "decisions",
        sa.Column("txn_id", sa.BigInteger(), nullable=False),
        sa.Column("tier", sa.String(length=8), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("requires_review", sa.Boolean(), nullable=False),
        sa.Column("mode", sa.String(length=12), nullable=False),
        sa.Column("decided_by", sa.String(length=64), nullable=False),
        sa.Column("model_tier", sa.String(length=8), nullable=True),
        sa.Column("risk", sa.Float(precision=53), nullable=True),
        sa.Column("risk_score", sa.Integer(), nullable=True),
        sa.Column("risk_band", sa.String(length=16), nullable=False),
        sa.Column("scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_version", sa.String(length=16), nullable=True),
        sa.Column("policy_version", sa.String(length=16), nullable=False),
        sa.Column("scenario", sa.String(length=16), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("narrative", sa.Text(), nullable=True),
        sa.Column("features", postgresql.ARRAY(sa.Float(precision=53)), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=True),
        sa.Column("customer_response", sa.String(length=8), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "customer_response IS NULL OR customer_response IN ('proceed', 'cancel')",
            name=op.f("ck_decisions_customer_response"),
        ),
        sa.CheckConstraint(
            "tier IN ('allow', 'warn', 'step_up', 'hold')", name=op.f("ck_decisions_tier")
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_decisions_case_id_cases")),
        sa.ForeignKeyConstraint(
            ["txn_id"],
            ["transactions.txn_id"],
            name=op.f("fk_decisions_txn_id_transactions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("txn_id", name=op.f("pk_decisions")),
    )
    op.create_index(
        "ix_decisions_alerts",
        "decisions",
        [sa.literal_column("decided_at DESC")],
        unique=False,
        postgresql_where=sa.text("tier <> 'allow'"),
    )
    op.create_index(
        "ix_decisions_case",
        "decisions",
        ["case_id"],
        unique=False,
        postgresql_where=sa.text("case_id IS NOT NULL"),
    )
    op.create_table(
        "freeze_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wallet_id", sa.String(length=32), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=12), server_default="pending", nullable=False),
        sa.Column("requested_by", sa.Integer(), nullable=False),
        sa.Column("decided_by", sa.Integer(), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'pending') = (decided_by IS NULL)",
            name=op.f("ck_freeze_requests_decided_has_decider"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected')", name=op.f("ck_freeze_requests_status")
        ),
        sa.CheckConstraint(
            "decided_by IS NULL OR decided_by <> requested_by",
            name=op.f("ck_freeze_requests_two_person"),
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_freeze_requests_case_id_cases")
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"], ["users.id"], name=op.f("fk_freeze_requests_decided_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"], ["users.id"], name=op.f("fk_freeze_requests_requested_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"], ["wallets.wallet_id"], name=op.f("fk_freeze_requests_wallet_id_wallets")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_freeze_requests")),
    )
    op.create_index(
        "uq_freeze_requests_pending_wallet",
        "freeze_requests",
        ["wallet_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "wallet_flags",
        sa.Column("wallet_id", sa.String(length=32), nullable=False),
        sa.Column("flagged_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.String(length=40), nullable=False),
        sa.Column("source", sa.String(length=12), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=True),
        sa.Column("applied_seq", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('history', 'replay', 'upstream', 'case')",
            name=op.f("ck_wallet_flags_source"),
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_wallet_flags_case_id_cases")
        ),
        sa.PrimaryKeyConstraint("wallet_id", name=op.f("pk_wallet_flags")),
    )
    op.create_index("ix_wallet_flags_flagged_at", "wallet_flags", ["flagged_at"], unique=False)
    # ### end Alembic commands ###

    # The audit trail is append-only for everyone, including the application's own role.
    op.execute(
        """
        CREATE FUNCTION audit_log_is_append_only() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_log is append-only';
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_log_no_change BEFORE UPDATE OR DELETE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION audit_log_is_append_only()
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_log_no_truncate BEFORE TRUNCATE ON audit_log
        FOR EACH STATEMENT EXECUTE FUNCTION audit_log_is_append_only()
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TABLE IF EXISTS audit_log CASCADE")
    op.execute("DROP FUNCTION IF EXISTS audit_log_is_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_wallet_flags_flagged_at", table_name="wallet_flags")
    op.drop_table("wallet_flags")
    op.drop_index(
        "uq_freeze_requests_pending_wallet",
        table_name="freeze_requests",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_table("freeze_requests")
    op.drop_index(
        "ix_decisions_case", table_name="decisions", postgresql_where=sa.text("case_id IS NOT NULL")
    )
    op.drop_index(
        "ix_decisions_alerts", table_name="decisions", postgresql_where=sa.text("tier <> 'allow'")
    )
    op.drop_table("decisions")
    op.drop_index(op.f("ix_customer_reports_reporter_id"), table_name="customer_reports")
    op.drop_index(op.f("ix_customer_reports_reported_wallet_id"), table_name="customer_reports")
    op.drop_table("customer_reports")
    op.drop_index(op.f("ix_case_events_case_id"), table_name="case_events")
    op.drop_table("case_events")
    op.drop_index(
        "uq_cases_open_subject", table_name="cases", postgresql_where=sa.text("status <> 'closed'")
    )
    op.drop_index("ix_cases_status_sla", table_name="cases")
    op.drop_table("cases")
    op.drop_table("wallets")
    op.drop_table("users")
    op.drop_index("ix_transactions_sender_ts", table_name="transactions")
    op.drop_index("ix_transactions_receiver_ts", table_name="transactions")
    op.drop_index(
        "ix_transactions_applied",
        table_name="transactions",
        postgresql_where=sa.text("applied_seq IS NOT NULL"),
    )
    op.drop_table("transactions")
    op.drop_index(op.f("ix_past_cases_mule_id"), table_name="past_cases")
    op.drop_table("past_cases")
    op.drop_table("agents")
    # ### end Alembic commands ###
